import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ReactDOM from 'react-dom';
import Navbar from "../components/navbar"


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>

      <div className={styles.content}></div>

      <footer className={styles.footer}>
        Developed by{' '}
        <span className={styles.logo}>
          Group xx
        </span>
      </footer>
    </div >
  )
}

export default Home
